services:
  jupyter:
    container_name: jupyter
    build:
      context: .
    working_dir: /app
    tty: true
    volumes:
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
        - "$JUPYTER_PORT:$JUPYTER_PORT"
    env_file:
     - .env
    entrypoint: jupyter lab --ip 0.0.0.0 --port=$JUPYTER_PORT --no-browser --allow-root
  tensorboard:
    container_name: tensorboard
    build:
      context: .
    working_dir: /logs
    tty: true
    volumes:
      - ./generated/tensors:/logs
    ports:
        - "$TENSORBOARD_PORT:$TENSORBOARD_PORT"
    env_file:
     - .env
    entrypoint: tensorboard --logdir "." --host 0.0.0.0 --port $TENSORBOARD_PORT
